---
    name: Continuous Integration
    
    on:
      push:
        branches:
          - main
          - "dev-*"
      workflow_dispatch:
    
    jobs:
      build-and-lint:
        name: Build and Lint
        runs-on: ubuntu-22.04
    
        steps:
          - name: Download code
            uses: actions/checkout@v4
        
          - name: Run Hadolint
            run: ls -la
