---
    name: Continuous Integration
    
    on:
      push:
        branches:
          - main
          - "dev-*"
      workflow_dispatch:
    
    jobs:
      build-code:
        name: Build Code
        runs-on: ubuntu-22.04
    
        steps:
          - name: Download code
            uses: actions/checkout@v4
        
          - name: Run public Docker image
            uses: docker/run-action@v3
            with:
              args: --rm -i hadolint/hadolint < Dockerfile
