---
    name: Continuous Integration
    
    on:
      push:
        branches:
          - main
          - "dev-*"
      workflow_dispatch:
    
    jobs:
      build-and-lint:
        name: Build and Lint
        runs-on: ubuntu-22.04
    
        steps:
          - name: Download code
            uses: actions/checkout@v4
          
          - name: Run Hadolint
            uses: hadolint/hadolint-action@v3.1.0
            with:
              dockerfile: Dockerfile

          - name: View output
            run: cat /dev/stdout
